name: group_listview
description: Flutter package for grouped list view
version: 0.0.1
author: Daniel Ioannou
homepage: https://github.com/Daniel-Ioannou

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: